### PR TITLE
docs(website): remove duplicate architecture.md

### PR DESCRIPTION
**Pull request by mandarvaze**
Add missing `title` to the frontmatter

## Description of change

Added `title` to address the failing CI build due to missing `title` front matter in the `architecture.md

## How has this been tested? (if applicable)

Not tested.

### CODE REVIEW

**Comment by orhun** [comment]
Ah, this should be now at the root of the repository. Can you remove that file instead?

**Comment by mandarvaze** [comment]
@orhun Do you want me to remove `website/src/content/docs/architecture.md` ?

**Comment by orhun** [comment]
yessir

**Comment by mandarvaze** [comment]
Done ✅  @orhun

**Review by orhun — APPROVED** [review]
Thanks! :)

**Pull request merged**
