### PR TITLE
feat(ui): support shift+tab for going to the previous tab

### LINKED ISSUE #63: shift+tab for scrolling a tab back
As discussed on the discord server, maybe having a way to just scroll back a tab instead of scrolling the entire view till the first one would be a better user experience! -> that would be `tab` to move forwards, `shift+tab` - or something else - to move backwards

### PR DESCRIPTION
**Pull request by XXMA16**
## Description of change

Implemented Shift+Tab for scrolling a tab back
Closes #63

## Concerns

- Changed the `if else`'s in `HexdumpCommand#parse` to a `match`
- `ShiftTab -> Back` takes up a lot of space and might be a weird name
- `CancelPrevious` doesn't really need a `check_sub` since Hexdump is not the first tab

### CODE REVIEW

**Review by orhun — COMMENTED** [review]
LGTM!

> ShiftTab -> Back takes up a lot of space and might be a weird name

"Previous" is better :) (Bksp also uses "back") 

Also, instead of adding ShiftTab it to the every tab, we can maybe add it only to General, to keep things short. 

Another thing, I think it should come after "Tab->Next".

**Comment by XXMA16** [comment]
Should I change `ShiftTab` to `⇧+Tab`?

**Comment by orhun** [comment]
Hmm, that's actually a good idea :)

**Review by orhun — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
